name: Publish ASN IP Ranges
permissions: write-all

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: Run ASN2IP Script
        run: |
         echo pwsh -version
         
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run ASN2IP Script
        run: |
         pwsh -version |
         Set-PSDebug -Trace 2 |
         pwsh -Command "./ASN2IP.ps1 -ExecutionPolicy bypass -ORGANIZATION_NAME "microsoft""
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_id }}-${{ github.run_number }}
          release_name: ${{ github.run_id }}-${{ github.run_number }}
          draft: false
          prerelease: false
          
      - name: Build Artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./asn_ip_ranges.txt
          asset_name: asn_ip_ranges.txt
          asset_content_type: text/plain
